
name: CDF Flow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simple:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Lint
        run: |
          make test-lint
      - name: Unit testing
        run: |
          make test-unit
  integration:
    runs-on: ubuntu-latest
    needs: simple
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        az-cli-version: [2.24.2, 2.23.0, 2.22.1]
        terraform-version: [1.0.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Install AZ, bicep & terraform
        run: |
          pip install azure-cli==${{matrix.az-cli-version}}
          az bicep install
          az --version
          curl -L https://releases.hashicorp.com/terraform/${{ matrix.terraform-version }}/terraform_${{ matrix.terraform-version }}_linux_amd64.zip -o /tmp/terraform_${{ matrix.terraform-version }}_linux_amd64.zip
          unzip /tmp/terraform_${{ matrix.terraform-version }}_linux_amd64.zip -d ~/bin
          terraform --version
      - name: Install CDF
        run: |
          pip install wheel
          make build
          make install
          az cdf debug version
      - name: Integration testing
        run: |
          az login --service-principal --username ${{ secrets.ARM_CLIENT_ID }} --password ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }} -o none
          export ARM_CLIENT_ID="${{ secrets.ARM_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.ARM_CLIENT_SECRET }}"
          export ARM_SUBSCRIPTION_ID="${{ secrets.ARM_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ secrets.ARM_TENANT_ID }}"
          make test-integration
