# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simple:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        # az-cli-version: [2.24.0, 2.23.0, 2.22.1]
        az-cli-version: [2.24.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Lint
        run: |
          make test-lint
      - name: unit testing
        run: |
          make test-unit
  integration:
    runs-on: ubuntu-latest
    needs: simple
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        az-cli-version: [2.24.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: install AZ
        run: |
          echo "install azure-cli"
          pip install azure-cli==${{matrix.az-cli-version}}
          az --version
      - name: install CDF
        run: |
          pip install wheel
          make build
          make install
          ls -l 
          ls -l ./dist/*
          az cdf --version
      # - name: integration testing
      #   run: |
      #     make test-unit
