# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simple:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Lint
        run: |
          make test-lint
      - name: Unit testing
        run: |
          make test-unit
  integration:
    runs-on: ubuntu-latest
    needs: simple
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        az-cli-version: [2.24.2, 2.23.0, 2.22.1]
        terraform-version: [0.15.5]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Install AZ, bicep & terraform
        run: |
          pip install azure-cli==${{matrix.az-cli-version}}
          az bicep install
          az --version
          curl -L https://releases.hashicorp.com/terraform/${{terraform-version}}/terraform_${{terraform-version}}_linux_amd64.zip -o /tmp/terraform_${{terraform-version}}_linux_amd64.zip
          unzip /tmp/terraform_${{terraform-version}}_linux_amd64.zip -d /usr/bin
          terraform --version
      - name: Install CDF
        run: |
          pip install wheel
          make build
          make install
          az cdf debug version
      - name: Integration testing
        run: |
          az login --service-principal --username ${{ secrets.APP_ID }} --password ${{ secrets.APP_PASSWORD }} --tenant ${{ secrets.APP_TENANT_ID }} -o none
          make test-integration
